name: odoo-infrastructure-backup
services:
  backup:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backup
    env_file: ../env/.env.backup
    volumes:
      - odoo-data:/filestore:ro
      - /srv/odoo-backups:/backups
    mem_limit: 1g
    cpus: 1.0
    networks:
      - internal

networks:
  internal:
    external: true
    name: odoo-shared

volumes:
  odoo-data:
    external: true
    name: odoo-data
